/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SimpleCalculator;

import java.util.Scanner;

public class Calculator {
    public static void main(String[] args) {
    	double num1,num2; char operator;
    	Scanner input = new Scanner(System.in);
    	
    	System.out.println("\tWELCOME TO TPRDc CALCULTOR");
    	System.out.println();
    	
    	System.out.print("ENTER OPERATOR[+ , - , * ,/]: ");
    	operator=input.next().charAt(0);
    	
    	System.out.print("ENTER NUMBER: ");
    	num1=input.nextInt();
    	
    	System.out.print("ENTER NUMBER: ");
    	num2=input.nextInt();
    	
    	switch(operator){
    	case '+':
    		System.out.printf("%.0f + %.0f = %.0f" , num1,num2,(num1+num2));
    		break;
    	case '-':
    		System.out.printf("%.0f - %.0f = %.0f" , num1,num2,(num1-num2));
    		break;
    	case '*':
    		System.out.printf("%.0f x %.0f = %.0f" , num1,num2,(num1*num2));
    		break;
    	case '/':
    		if(num2!=0)
    			System.out.printf("%.0f / %.0f = %.2f" , num1,num2,(num1/num2));
    		else
    			System.out.println("math error, can not be divied by zero");
    		break;
    	default:
    		System.out.println(operator+"IS AN INVAID OPERATOR");
    	}
    	
    }
}